dolma -c th_c4_v3.json tag 
dolma -c thai_char_ratio_doc_v1.json tag
dolma -c th_gopher_v3.json tag
dolma -c thai_gamble_document_v4.json tag
dolma -c thai_porn_document_v3.json tag
dolma -c dedupe_by_url.json dedupe
dolma -c dedupe_docs.json dedupe
dolma -c th_pii_regex_with_counts_fast_v2.json tag
dolma -c thai_gamble_document_v4.json tag
dolma -c thai_porn_document_v3.json tag
dolma -c mix-data.json mix